# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none
pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: REMOTE_STATE_LOCATION
    displayName: 
    type: string
    default: uksouth
    values:  
    - uksouth
    - ukwest
  - name: module
    displayName: 'Infra to be created'  
    default: storageaccount
    values:  
    - keyvault
    - appgateway  
  - name: environment
    displayName: 
    default: QA
    values:  
    - DEV
    - PROD      

variables:
- group: ARM-SUBSCRIPTION
- name: teamname
- name: REMOTE_STATE_RESOURCE_GROUP
  value: "${{ parameters.REMOTE_STATE_LOCATION }}${{ parameters.environment }}${{ parameters.environment }}-rg"
- name: REMOTE_STATE_STORAGE_ACCOUNT
  value: "${{ parameters.REMOTE_STATE_LOCATION }}${{ parameters.environment }}${{ parameters.environment }}"
- name: REMOTE_STATE_STORAGE_CONTAINER
  value: "${{ parameters.REMOTE_STATE_LOCATION }}${{ parameters.environment }}${{ parameters.environment }}_container"

stages:

# ---------------------------------------------------------------------------------------------------------------------
# Initalization stage
#
# Initialize a resource group with a storage account and a container that will be used as remote state.
# Terraform needs to store it's state somewhere to keep track of the infrastructure, with this stage we ensure that
# the remote state will be created.
# ---------------------------------------------------------------------------------------------------------------------

- stage: Init
  jobs:
  - job: InitRemoteState
    steps:    
    - script: |
        chmod +x ./scripts/backend.sh 
      displayName: 'Enable script permissions'

   

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: './scripts/backend.sh "${{ parameters.REMOTE_STATE_LOCATION }}" "${{ variables.REMOTE_STATE_RESOURCE_GROUP }}" "${{ variables.REMOTE_STATE_STORAGE_ACCOUNT }}" "${{ variables.REMOTE_STATE_STORAGE_CONTAINER }}"'
      displayName: 'Init remote state'
